[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  VITE_API_URL = "https://inventory-manager-bks2.onrender.com"
  NODE_VERSION = "18"
